Update .ruby-version
update jruby version.
If using jruby 1.6.8, there is an error when you are installing rawr.
ERROR: Error installing rubyzip:
rubyzip requires Ruby version >= 1.9.2.